/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import com.mittbant.cocochatcliente.Cliente;
import com.mittbant.cocochatcliente.GuardadorConversaciones;
import com.mittbant.cocochatcliente.Mensaje;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPopupMenu;
import javax.swing.JTextField;
import javax.swing.JTextPane;

/**
 *
 * @author felixramosscalabrin
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form chat_
     */
    public home() {
        initComponents();
        
        this.jbtn_agregaramigo.setVisible(false);
        
        Cliente.llenaListaAmigos(this.Amigos_List_amigos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Conectados = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        Desconectados = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        Send_msg = new javax.swing.JButton();
        Message_Chat = new javax.swing.JTextField();
        Mensajes_chat = new javax.swing.JButton();
        Todos_pane = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Todos_list_conectados = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Todos_List_Desconectados = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Amigos_List_amigos = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        Grupos_bttn_NuevoGrupo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        Misgrupos_List_misgrupos = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        Grupos_list_Grupos = new javax.swing.JList<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        Message_view = new javax.swing.JTextPane();
        Jlbl_nombreconversacion = new javax.swing.JLabel();
        Jlbl_minombre = new javax.swing.JLabel();
        jbtn_agregaramigo = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jTree1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jMenuItem1.setText("Agregar a amigos");
        Conectados.add(jMenuItem1);
        Conectados.add(jSeparator1);

        jMenuItem3.setText("Enviar Mensaje");
        Conectados.add(jMenuItem3);

        jMenuItem2.setText("Agregar a amigos");
        Desconectados.add(jMenuItem2);
        Desconectados.add(jSeparator2);

        jMenuItem4.setText("Enviar mensaje");
        Desconectados.add(jMenuItem4);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Send_msg.setText("Mandar");
        Send_msg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Send_msgActionPerformed(evt);
            }
        });

        Message_Chat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Message_ChatKeyPressed(evt);
            }
        });

        Mensajes_chat.setText("Mensajes");
        Mensajes_chat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mensajes_chatActionPerformed(evt);
            }
        });

        Todos_list_conectados.setComponentPopupMenu(Conectados);
        Todos_list_conectados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Todos_list_conectados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Todos_list_conectadosMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(Todos_list_conectados);

        jLabel1.setText("Conectados");

        jLabel2.setText("Desconectados");

        Todos_List_Desconectados.setComponentPopupMenu(Desconectados);
        jScrollPane5.setViewportView(Todos_List_Desconectados);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(jLabel1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );

        Todos_pane.addTab("Todos", jPanel3);

        jLabel3.setText("Amigos");

        Amigos_List_amigos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Amigos_List_amigos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Amigos_List_amigosMousePressed(evt);
            }
        });
        jScrollPane6.setViewportView(Amigos_List_amigos);

        jButton1.setText("Refrescar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(117, 117, 117))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addContainerGap())
        );

        Todos_pane.addTab("Amigos", jPanel4);

        Grupos_bttn_NuevoGrupo.setText("+");
        Grupos_bttn_NuevoGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grupos_bttn_NuevoGrupoActionPerformed(evt);
            }
        });

        jLabel4.setText("Mis Grupos");

        Misgrupos_List_misgrupos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(Misgrupos_List_misgrupos);

        jLabel5.setText("Grupos");

        Grupos_list_Grupos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(Grupos_list_Grupos);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                                .addComponent(Grupos_bttn_NuevoGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Grupos_bttn_NuevoGrupo)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        Todos_pane.addTab("Grupos", jPanel5);

        jScrollPane9.setViewportView(Message_view);

        jbtn_agregaramigo.setText("Agregar");
        jbtn_agregaramigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_agregaramigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Todos_pane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Jlbl_minombre)
                        .addGap(251, 251, 251)
                        .addComponent(Mensajes_chat, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(Jlbl_nombreconversacion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Message_Chat, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Send_msg))
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbtn_agregaramigo)
                                .addGap(15, 15, 15)))))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Mensajes_chat)
                                .addComponent(Jlbl_nombreconversacion))
                            .addComponent(Jlbl_minombre, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Todos_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jbtn_agregaramigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Message_Chat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Send_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Mensajes_chatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mensajes_chatActionPerformed
        //TODO add your handling code here:
        Soliciudes_frame a = new Soliciudes_frame();
        a.setVisible(true);
        
    }//GEN-LAST:event_Mensajes_chatActionPerformed

    private void Grupos_bttn_NuevoGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grupos_bttn_NuevoGrupoActionPerformed
        // TODO add your handling code here:
        NvoGrupo_frame s = new NvoGrupo_frame();
        s.setVisible(true);
       
    }//GEN-LAST:event_Grupos_bttn_NuevoGrupoActionPerformed

    private void Todos_list_conectadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Todos_list_conectadosMousePressed
        
        this.jbtn_agregaramigo.setVisible(true);
        
        if(this.Todos_list_conectados.getSelectedIndex()== -1)
            return;
        
        
        
        this.getJlbl_nombreconversacion().setText(this.Todos_list_conectados.getSelectedValue());
        Cliente.abreConversacion(this.Todos_list_conectados.getSelectedValue(), Message_view);
        
        try {
            if(Cliente.isFriend(this.Jlbl_nombreconversacion.getText()) 
                    //|| this.Jlbl_nombreconversacion.getText().equals(this.Jlbl_minombre.getText())
                    )
                this.jbtn_agregaramigo.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_Todos_list_conectadosMousePressed

    private void Send_msgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Send_msgActionPerformed
        
        sendMessage();
        
        
    }//GEN-LAST:event_Send_msgActionPerformed

    private void Message_ChatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Message_ChatKeyPressed
        
        
        if(evt.getKeyChar()==10){
        sendMessage();
        }
    }//GEN-LAST:event_Message_ChatKeyPressed

    private void jbtn_agregaramigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_agregaramigoActionPerformed
        if(this.Jlbl_nombreconversacion.getText().isEmpty())
            return ;
        
        
        Cliente.sendRequest(this.Jlbl_nombreconversacion.getText());
        this.jbtn_agregaramigo.setVisible(false);
        
        
    }//GEN-LAST:event_jbtn_agregaramigoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Cliente.llenaListaAmigos(Amigos_List_amigos);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Amigos_List_amigosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Amigos_List_amigosMousePressed
        this.jbtn_agregaramigo.setVisible(false);
        
        if(this.Amigos_List_amigos.getSelectedIndex()== -1)
            return;
        
        
        
        this.getJlbl_nombreconversacion().setText(this.Amigos_List_amigos.getSelectedValue());
        Cliente.abreConversacion(this.Amigos_List_amigos.getSelectedValue(), Message_view);
        
        
    }//GEN-LAST:event_Amigos_List_amigosMousePressed

    
    private void sendMessage(){
        
        if(this.Message_Chat.getText().isEmpty() ||  this.Jlbl_nombreconversacion.getText().isEmpty())
            return;
        
        
        Cliente.mandaMensaje(this.Message_Chat.getText(), this.Jlbl_nombreconversacion.getText());
        
        GuardadorConversaciones.GuardaMensaje(new Mensaje(this.Jlbl_minombre.getText(),
                                                    this.Message_Chat.getText(),
                                                    this.Jlbl_nombreconversacion.getText() 
                                                    ));
            Cliente.abreConversacion(this.Jlbl_nombreconversacion.getText(), Message_view);
            this.Message_Chat.setText("");
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> Amigos_List_amigos;
    private javax.swing.JPopupMenu Conectados;
    private javax.swing.JPopupMenu Desconectados;
    private javax.swing.JButton Grupos_bttn_NuevoGrupo;
    private javax.swing.JList<String> Grupos_list_Grupos;
    private javax.swing.JLabel Jlbl_minombre;
    private javax.swing.JLabel Jlbl_nombreconversacion;
    private javax.swing.JButton Mensajes_chat;
    private javax.swing.JTextField Message_Chat;
    private javax.swing.JTextPane Message_view;
    private javax.swing.JList<String> Misgrupos_List_misgrupos;
    private javax.swing.JButton Send_msg;
    private javax.swing.JList<String> Todos_List_Desconectados;
    private javax.swing.JList<String> Todos_list_conectados;
    private javax.swing.JTabbedPane Todos_pane;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton jbtn_agregaramigo;
    // End of variables declaration//GEN-END:variables
    
    
    
    public JList<String> getAmigos_List_amigos() {
        return Amigos_List_amigos;
    }

    public void setAmigos_List_amigos(JList<String> Amigos_List_amigos) {
        this.Amigos_List_amigos = Amigos_List_amigos;
    }

    public JPopupMenu getConectados() {
        return Conectados;
    }

    public void setConectados(JPopupMenu Conectados) {
        this.Conectados = Conectados;
    }

    public JPopupMenu getDesconectados() {
        return Desconectados;
    }

    public void setDesconectados(JPopupMenu Desconectados) {
        this.Desconectados = Desconectados;
    }

    public JButton getGrupos_bttn_NuevoGrupo() {
        return Grupos_bttn_NuevoGrupo;
    }

    public void setGrupos_bttn_NuevoGrupo(JButton Grupos_bttn_NuevoGrupo) {
        this.Grupos_bttn_NuevoGrupo = Grupos_bttn_NuevoGrupo;
    }

    public JList<String> getGrupos_list_Grupos() {
        return Grupos_list_Grupos;
    }

    public void setGrupos_list_Grupos(JList<String> Grupos_list_Grupos) {
        this.Grupos_list_Grupos = Grupos_list_Grupos;
    }

    public JLabel getJlbl_minombre() {
        return Jlbl_minombre;
    }

    public void setJlbl_minombre(JLabel Jlbl_minombre) {
        this.Jlbl_minombre = Jlbl_minombre;
    }

    public JButton getMensajes_chat() {
        return Mensajes_chat;
    }

    public void setMensajes_chat(JButton Mensajes_chat) {
        this.Mensajes_chat = Mensajes_chat;
    }

    public JTextField getMessage_Chat() {
        return Message_Chat;
    }

    public void setMessage_Chat(JTextField Message_Chat) {
        this.Message_Chat = Message_Chat;
    }

    public JTextPane getMessage_view() {
        return Message_view;
    }

    public void setMessage_view(JTextPane Message_view) {
        this.Message_view = Message_view;
    }

    public JList<String> getMisgrupos_List_misgrupos() {
        return Misgrupos_List_misgrupos;
    }

    public void setMisgrupos_List_misgrupos(JList<String> Misgrupos_List_misgrupos) {
        this.Misgrupos_List_misgrupos = Misgrupos_List_misgrupos;
    }

    public JButton getSend_msg() {
        return Send_msg;
    }

    public void setSend_msg(JButton Send_msg) {
        this.Send_msg = Send_msg;
    }

    public JList<String> getTodos_List_Desconectados() {
        return Todos_List_Desconectados;
    }

    public void setTodos_List_Desconectados(JList<String> Todos_List_Desconectados) {
        this.Todos_List_Desconectados = Todos_List_Desconectados;
    }

    public JList<String> getTodos_list_conectados() {
        return Todos_list_conectados;
    }

    public void setTodos_list_conectados(JList<String> Todos_list_conectados) {
        this.Todos_list_conectados = Todos_list_conectados;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public void setButtonGroup1(ButtonGroup buttonGroup1) {
        this.buttonGroup1 = buttonGroup1;
    }

    public JLabel getJlbl_nombreconversacion() {
        return Jlbl_nombreconversacion;
    }

    public void setJlbl_nombreconversacion(JLabel Jlbl_nombreconversacion) {
        this.Jlbl_nombreconversacion = Jlbl_nombreconversacion;
    }





}



